#ifndef BASE_H_
#define BASE_H_

// SpinDec includes

// Generated automatically using update-base.sh
// Seto Balian, Oct 23, 2014

#include <Eigen/Dense>

#include "SpinDec/AdiabaticLabel.h"
#include "SpinDec/BoostEigen.h"
#include "SpinDec/CCE.h"
#include "SpinDec/CPMG.h"
#include "SpinDec/CPMGDephasing.h"
#include "SpinDec/CSDProblem.h"
#include "SpinDec/Cluster.h"
#include "SpinDec/ClusterDatabase.h"
#include "SpinDec/ClusterDatabaseEntry.h"
#include "SpinDec/CrystalBasis.h"
#include "SpinDec/CrystalStructure.h"
#include "SpinDec/DensityOperator.h"
#include "SpinDec/DiamondCubic.h"
#include "SpinDec/Dipolar.h"
#include "SpinDec/Eigenspectrum.h"
#include "SpinDec/ElectronSpinParameters.h"
#include "SpinDec/Errors.h"
#include "SpinDec/EvolutionOperator.h"
#include "SpinDec/FileProperties.h"
#include "SpinDec/FreeEvolution.h"
#include "SpinDec/HermitianEigenspectrum.h"
#include "SpinDec/Hyperfine.h"
#include "SpinDec/HyperfineParameters.h"
#include "SpinDec/IdentityOperator.h"
#include "SpinDec/IdentityPulse.h"
#include "SpinDec/IsingHyperfine.h"
#include "SpinDec/LatticeVectors.h"
#include "SpinDec/MatrixRepresentation.h"
#include "SpinDec/NuclearSpinParameters.h"
#include "SpinDec/PiPulse.h"
#include "SpinDec/Pulse.h"
#include "SpinDec/PulseExperiment.h"
#include "SpinDec/PulseSequence.h"
#include "SpinDec/PulseSequenceBase.h"
#include "SpinDec/RandomNumberGenerator.h"
#include "SpinDec/ReducedProblem.h"
#include "SpinDec/Sign.h"
#include "SpinDec/SimpleCubicLatticeVectors.h"
#include "SpinDec/SpinBasis.h"
#include "SpinDec/SpinBath.h"
#include "SpinDec/SpinDonor.h"
#include "SpinDec/SpinDown.h"
#include "SpinDec/SpinHalf.h"
#include "SpinDec/SpinHalfParameters.h"
#include "SpinDec/SpinHalfStates.h"
#include "SpinDec/SpinHamiltonian.h"
#include "SpinDec/SpinInteraction.h"
#include "SpinDec/SpinInteractionEdge.h"
#include "SpinDec/SpinInteractionGraph.h"
#include "SpinDec/SpinInteractionVertex.h"
#include "SpinDec/SpinOperator.h"
#include "SpinDec/SpinParameters.h"
#include "SpinDec/SpinParametersVector.h"
#include "SpinDec/SpinState.h"
#include "SpinDec/SpinSystem.h"
#include "SpinDec/SpinSystemBase.h"
#include "SpinDec/SpinUp.h"
#include "SpinDec/StringOptions.h"
#include "SpinDec/TimeArray.h"
#include "SpinDec/TimeEvolution.h"
#include "SpinDec/TwoStateSuperposition.h"
#include "SpinDec/UniformMagneticField.h"
#include "SpinDec/constants.h"
#include "SpinDec/options.h"
#include "SpinDec/typedefs.h"

#endif // BASE_H_

